#!/usr/bin/env bash
# Portable OBS Studio launcher

# Check if we are in a container (toolbox/distrobox) and if we are running in our prepared container image
# See: https://github.com/ublue-os/obs-studio-portable/blob/main/obs-config-fix.sh
if [ -f /run/.containerenv ] && [ -x /etc/profile.d/99-obs-config-fix.sh ]; then
    /etc/profile.d/99-obs-config-fix.sh
fi

if [ -e /etc/os-release ] && grep --quiet UBUNTU_CODENAME /etc/os-release; then
    DISTRO_CODENAME=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g')
    if [ "${DISTRO_CODENAME}" != "TARGET_CODENAME" ]; then
        echo "ERROR! $(basename "${0}") is only compatible with distribution built on Ubuntu TARGET_CODENAME not ${DISTRO_CODENAME}."
        exit 1
    fi
else
    echo "ERROR! Unsupported Linux distribution."
    exit 1
fi

PORTABLE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
export LD_LIBRARY_PATH="${PORTABLE_DIR}/bin/64bit":"${PORTABLE_DIR}/obs-plugins/64bit":"${PORTABLE_DIR}/data/obs-scripting/64bit":"${PORTABLE_DIR}/cef":"${PORTABLE_DIR}/lib"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

if [ ! -d "${PORTABLE_DIR}/bin/64bit" ]; then
    echo "ERROR! Could not find ${PORTABLE_DIR}/bin/64bit."
    exit 1
fi

cd "${PORTABLE_DIR}/bin/64bit"
exec ./obs --portable "${@}"
